// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: job_posts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createJobPost = `-- name: CreateJobPost :one
INSERT INTO job_posts (id, title, company, location, level, minimum_qualifications, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id, title, company, location, level, minimum_qualifications, created_at
`

type CreateJobPostParams struct {
	ID                    uuid.UUID
	Title                 string
	Company               string
	Location              string
	Level                 string
	MinimumQualifications []string
	CreatedAt             time.Time
}

func (q *Queries) CreateJobPost(ctx context.Context, arg CreateJobPostParams) (JobPost, error) {
	row := q.db.QueryRowContext(ctx, createJobPost,
		arg.ID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Level,
		pq.Array(arg.MinimumQualifications),
		arg.CreatedAt,
	)
	var i JobPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Level,
		pq.Array(&i.MinimumQualifications),
		&i.CreatedAt,
	)
	return i, err
}
